##############################
# Development
##############################

version: "3.7"

networks:
  outline_network:

services:
  redis:
    image: redis
    ports:
      - "6479:6379"
    restart: unless-stopped
    volumes:
      - outline_redis:/data
    networks:
      - outline_network

  postgres:
    image: postgres
    ports:
      - "5532:5432"
    restart: unless-stopped
    volumes:
      - outline_postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: outline
    networks:
      - outline_network

  s3:
    image: lphoward/fake-s3
    ports:
      - "4569:4569"
    restart: unless-stopped
    volumes:
      - ./fakes3:/fakes3_root
    networks:
      - outline_network

  outline:
    image: outline:v001
    command: yarn dev
    build:
      context: .
      dockerfile: Dockerfile
      args:
        pull: 1
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - .:/opt/outline
    depends_on:
      - postgres
      - redis
      - s3
    networks:
      - outline_network

  adminer:
    image: adminer
    restart: always
    ports:
      - 2929:8080
    networks:
      - outline_network

volumes:
  outline_postgres:
  outline_redis:
